### PR TITLE
Add entity relationship diagram

### PR DESCRIPTION
**Pull request by Grifo89**
Entity relationship diagram added.

### CODE REVIEW

**Comment by samgaco** [comment]
Hi @Grifo89 and @edemagbenyo :high_brightness: 

Some things to address:

- [ ] The linter checks should be green

- [ ] The ERD should be within a `/docs` folder inside the project. [Requirement](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone1/erd2.png).

- [ ] The friendship model has two primary keys, it should have only one, not being the receiver nor the sender

- [ ] What's the use of the table profiles? since a user should have only one profile it would already be ok to include all those features within the user table, right?


Please, work on these fixes and submit back for another review once you are done :+1: 

----------------------------
* ###### STATUS OF THE PROJECT: REQUESTED CHANGES :stop_sign:

**Comment by Grifo89** [comment]
@samgaco remember that it is also right to use a composite primary key, check out the videos suggested by Microverse curriculum

**Comment by Grifo89** [comment]
@samgaco regarding profile table it could be a way to do it or is there something that says that is wrong?

**Comment by samgaco** [comment]
Hi @Grifo89 , you can continue with the profile table if you wish, I was just stating it in case you did not have it clear :+1: 

And for the primary key thing, I was suggesting a primary key (id for a friendship) , but if you want to go on with the foreign keys set also as primary keys, that is ok, but remember you could do that too with just the id of the friendships. Please work on the other changes and submit for another review :100:

**Comment by Grifo89** [comment]
@samgaco I just want to suggest that you should specify which corrections are optional and which are not. Anyway, thank you for your review.

**Pull request merged**
